export { default as ChangeLanguage } from "./ChangeLanguage"
export { default as ChangeCurrency } from "./ChangeCurrency"
export { default as ChangeWallet, Footer as FooterChangeWallet } from "./ChangeWallet"
export { default as GenerateMnenonic } from "./GenerateMnenonic"
export { default as AddAccount } from "./AddAccount"
export { default as AddWatchAccount } from "./AddWatchAccount"
export { default as ChangeAvatar } from "./ChangeAvatar"
export { default as AddContact } from "./AddContact"
export { default as RemoveContact } from "./RemoveContact"
export { default as EditContact } from "./EditContact"
